SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS fileDiff (
  id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  diffTime   TIMESTAMP,
  sourceFile VARCHAR(1024) NOT NULL   DEFAULT '',
  targetFile VARCHAR(1024) NOT NULL   DEFAULT '',
  fileDiff   VARCHAR(2600) NOT NULL   DEFAULT ''
);